### Login
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "username": "danielko",
    "password": "test"
}

### Get all authors
GET http://localhost:8080/api/authors

### Get author
GET http://localhost:8080/api/authors/b65e7783-1bfd-4a29-9e40-8c670d202711

### Create a new author
PUT http://localhost:8080/api/authors
Content-Type: application/json

{
    "firstName": "David",
    "lastName": "Koller",
    "username": "kolly2"
}

### Update author
POST http://localhost:8080/api/authors/e0a77455-f22b-c8d4-e68e-73e8df692997
Content-Type: application/json

{
    "firstName": "David",
    "lastName": "Koller",
    "username": "kolly2"
}

### Delete author
DELETE http://localhost:8080/api/authors/d94e942c-864a-a824-6bc0-4a69ca2c6c4f

### Get all recipes
GET http://localhost:8080/api/recipes

### Get recipes filtered by author ID
GET http://localhost:8080/api/recipes?authorId=8cca86ae-6616-8a6b-d199-8a769d400255